=== codeGraphK/DAW/Lenguaje de marcas/Segundo Trimestre - XML/Ejercicios/DTD/Videoteca/videoteca.dtd
<!ELEMENT videoteca (cd+)>
<!ELEMENT cd (video+)>
<!ELEMENT video (director, actores?, duracion?, lista?)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT actores (actor+)>
<!ELEMENT actor EMPTY>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT lista (episodio+)>
<!ELEMENT episodio (titulo, duracion, estado, fechaestreno)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT estado EMPTY>
<!ELEMENT fechaestreno (#PCDATA)>

<!ATTLIST cd id ID #REQUIRED>
<!ATTLIST video type (pelicula|serie) "video">
<!ATTLIST video titulo CDATA #REQUIRED>
<!ATTLIST actor nombre CDATA "nombre">
<!ATTLIST actor genero (F|M|X) "X">
<!ATTLIST actor fechanacimiento CDATA #IMPLIED>
<!ATTLIST episodio id ID #REQUIRED>
<!ATTLIST episodio type (piloto|normal|extra|final) #REQUIRED>
<!ATTLIST estado estrenado (si|no) #REQUIRED>

=== codeGraphK/DAW/Lenguaje de marcas/Segundo Trimestre - XML/Ejercicios/DTD/Videoteca/04videoteca.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE videoteca SYSTEM "videoteca.dtd">
<videoteca>
    <cd id="x001">
        <video type="pelicula" titulo="La monda">
            <director></director>
            <actores>
                <actor nombre="" genero="F" fechanacimiento="" />
                <actor nombre="" genero="M" fechanacimiento="" />
            </actores>
            <duracion></duracion>
        </video>
        <video type="serie" titulo="La monda conti">
            <director></director>
            <actores>
                <actor nombre="" genero="F" fechanacimiento="" />
                <actor nombre="" genero="M" fechanacimiento="" />
            </actores>
            <lista>
                <episodio id="x101" type="piloto">
                    <titulo></titulo>
                    <duracion></duracion>
                    <estado estrenado="si" />
                    <fechaestreno></fechaestreno>
                </episodio>
            </lista>
        </video>
    </cd>
</videoteca>
