=== codeGraphK/DAW/Lenguaje de marcas/Segundo Trimestre - XML/Ejercicios/Schema/Almacen/almacen.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.almacen.es" xmlns="http://www.almacen.es" elementFormDefault="qualified">
    <xs:element name="almacen">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="productos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="producto" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="precio">
                                            <xs:complexType>
                                                <xs:attribute name="valor" type="xs:integer" />
                                                <xs:attribute name="moneda" type="xs:string" />
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="caracteristicas" minOccurs="0" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required" />
                                    <xs:attribute name="nohay" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="empresa" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== codeGraphK/DAW/Lenguaje de marcas/Segundo Trimestre - XML/Ejercicios/Schema/Almacen/02almacen.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<almacen empresa="asdasd" xmlns="http://www.almacen.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.almacen.es almacen.xsd">
   <productos>
      <producto id="A191">
         <nombre>Teclado</nombre>
         <precio valor="20" moneda="euros" />
         <caracteristicas>15 pulgadas</caracteristicas>
      </producto>
      <producto id="A167">
         <nombre>Monitor 14'</nombre>
         <precio valor="20000" moneda="pesetas" />
      </producto>
      <producto id="A180" nohay="A167">
         <nombre>Monitor 15'</nombre>
         <precio valor="20000" moneda="pesetas" />
      </producto>
   </productos>
</almacen>
