=== codeGraphK/DAW/Lenguaje de marcas/Segundo Trimestre - XML/Ejercicios/Schema/Productos/productos.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.productos.es" targetNamespace="http://www.productos.es" elementFormDefault="qualified">
    <xs:element name="productos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="precio" type="xs:decimal" />
                            <xs:element name="procedencia">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="provincia" type="xs:string" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="idProducto" type="xs:integer" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== codeGraphK/DAW/Lenguaje de marcas/Segundo Trimestre - XML/Ejercicios/Schema/Productos/productos.xml
<?xml version="1.0" ?>
<productos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.productos.es" xsi:schemaLocation="http://www.productos.es productos.xsd">
	<producto idProducto="100">
		<nombre>Tomate</nombre>
		<precio>0.6</precio>
		<procedencia>
			<provincia>Almeria</provincia>
			<provincia>Jaen</provincia>
		</procedencia>
	</producto>
	<producto idProducto="101">
		<nombre>Patata</nombre>
		<precio>0.8</precio>
		<procedencia>
			<provincia>Cordoba</provincia>
		</procedencia>
	</producto>
	<producto idProducto="102">
		<nombre>Lechuga</nombre>
		<precio>1.2</precio>
		<procedencia>
			<provincia>Malaga</provincia>
			<provincia>Sevilla</provincia>
			<provincia>Jaen</provincia>
		</procedencia>
	</producto>
</productos>
