=== codeGraphK/DAW/Lenguaje de marcas/Segundo Trimestre - XML/Ejercicios/Schema/newOnes/clientes.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns="http://www.clientes.es" targetNamespace="http://www.clientes.es" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="clientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cliente" type="clienteByDef" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:complexType name="clienteByDef">
        <xs:sequence>
            <xs:element name="nombre" type="nameFormat" />
            <xs:element name="apellido1" type="nameFormat" minOccurs="0" />
            <xs:element name="apellido2" type="nameFormat" minOccurs="0" />
            <xs:element name="direcciones" type="direcctionsFormat" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="idCliente" use="required" type="idFormat" />
        <xs:attribute name="dni" use="required" type="dniFormat" />
        <xs:attribute name="localidad" type="xs:string" />
        <xs:attribute name="sexo" type="sexoFormat" />
    </xs:complexType>

    <!-- <xs:complexType name="clienteDir">
        <xs:complexContent>
            <xs:extension base="clienteByDef">
                <xs:sequence>
                    <xs:element name="direcciones" type="direcctionsFormat" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType> -->


    <xs:simpleType name="nameFormat">
        <xs:restriction base="xs:string">
            <xs:maxLength value="15" />
            <xs:whiteSpace value="collapse" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dniFormat">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]{8})[a-z]" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idFormat">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[A-Z]([0-9]{7})" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="sexoFormat">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Hombre" />
            <xs:enumeration value="Mujer" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoFormat">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z]" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="direcctionsFormat">
        <xs:sequence>
            <xs:element name="direccion" type="direccFormat" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="numFormat">
        <xs:restriction base="xs:integer">
            <xs:minExclusive value="0"></xs:minExclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="direccFormat" mixed="true">
        <xs:sequence>
            <xs:element name="ciudad" type="xs:string" />
            <xs:element name="calle" type="xs:string" />
            <xs:element name="numero">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="numFormat">
                            <xs:attribute name="tipo" type="tipoFormat" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== codeGraphK/DAW/Lenguaje de marcas/Segundo Trimestre - XML/Ejercicios/Schema/newOnes/clientes.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<clientes xmlns="http://www.clientes.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.clientes.es clientes.xsd">
	<!--
 idcliente es un numero de entre 3 y 15 digitos
 dni 8 digitos y una letra
 sexo Hombre o Mujer
 tipo una letra
 el contenido del elemento numero tiene que ser mayor que 0 
 -->
	<cliente idCliente="A8142200" dni="11111111a" localidad="Madrid">
		<nombre>Antonio</nombre>
		<direcciones>
			<direccion>
				casa
				<ciudad>M�laga</ciudad>
				<calle>Larios</calle>
				<numero tipo="c">5</numero>
			</direccion>
			<direccion>
				trabajo
				<ciudad>Madrid</ciudad>
				<calle>Alcal�</calle>
				<numero tipo="c">120</numero>
			</direccion>
		</direcciones>
	</cliente>
	<cliente idCliente="B8155533" dni="22222222b" sexo="Hombre">
		<nombre>Jose Carlos</nombre>
		<apellido1>Mart�nez</apellido1>
	</cliente>
	<cliente idCliente="C8188878" dni="33333333c" sexo="Mujer">
		<nombre>Josefa</nombre>
		<apellido1>Mart�n</apellido1>
		<apellido2>Fern�ndez</apellido2>
	</cliente>
</clientes>
