=== codeGraphK/DAW/Lenguaje de marcas/Segundo Trimestre - XML/Ejercicios/Schema/Clientes/clientes.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.clientes.es" targetNamespace="http://www.clientes.es" elementFormDefault="qualified">
    <xs:element name="clientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cliente" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="direcciones" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="direccion" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="ciudad" type="xs:string" />
                                                    <xs:element name="calle" type="xs:string" />
                                                    <xs:element name="numero" type="xs:integer" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="apellido1" type="xs:string" minOccurs="0" />
                            <xs:element name="apellido2" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                        <xs:attribute name="idCliente" type="xs:integer" use="required" />
                        <xs:attribute name="dni" type="xs:integer" use="required" />
                        <xs:attribute name="localidad" type="xs:string" />
                        <xs:attribute name="sexo" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== codeGraphK/DAW/Lenguaje de marcas/Segundo Trimestre - XML/Ejercicios/Schema/Clientes/clientes.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.clientes.es" xsi:schemaLocation="http://www.clientes.es clientes.xsd">
	<cliente idCliente="81422" dni="11111111" localidad="Madrid">
		<nombre>Antonio</nombre>
		<direcciones>
			<direccion>
				<ciudad>M�laga</ciudad>
				<calle>Larios</calle>
				<numero>5</numero>
			</direccion>
			<direccion>
				<ciudad>Madrid</ciudad>
				<calle>Alcal�</calle>
				<numero>120</numero>
			</direccion>
		</direcciones>
	</cliente>
	<cliente idCliente="81555333" dni="22222222" sexo="Hombre">
		<nombre>Jose Carlos</nombre>
		<apellido1>Martinez</apellido1>
	</cliente>
	<cliente idCliente="81888" dni="33333333" sexo="Mujer">
		<nombre>Josefa</nombre>
		<apellido1>Martin</apellido1>
		<apellido2>Fernandez</apellido2>
	</cliente>
</clientes>
